//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atm.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public long OperationId { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> CardId { get; set; }
        public int OperationType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
